name: Cypress basic-tests Tests

on:
    schedule:
    - cron: '58 17 * * *' #ejecuta la pipeline todos los días a hora UTC
    workflow_dispatch:

jobs:
  cypress-basictests: #nombre de la pipipeline
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Run Cypress basic-tests
      run: npm run cy:basic-tests

    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mochawesome-report
        path: cypress/reports/html/index.html
        retention-days: 30 #el reporte se guardará por 30 días
        if-no-files-found: warn #si no se creó el reporte, no se generará un error/warning en la pipeline

      env:
        CI: true